// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceParticipationAPI.Data;

#nullable disable

namespace RaceParticipationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609113340_SeedLewisHamilton")]
    partial class SeedLewisHamilton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RaceParticipationAPI.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            Date = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Silverstone, UK",
                            Name = "British Grand Prix"
                        },
                        new
                        {
                            RaceId = 2,
                            Date = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Monte Carlo, Monaco",
                            Name = "Monaco Grand Prix"
                        });
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.RaceParticipation", b =>
                {
                    b.Property<int>("RacerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinishTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("RacerId", "TrackRaceId");

                    b.HasIndex("TrackRaceId");

                    b.ToTable("RaceParticipations");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            TrackRaceId = 1,
                            FinishTimeInSeconds = 5460,
                            Position = 1
                        },
                        new
                        {
                            RacerId = 1,
                            TrackRaceId = 2,
                            FinishTimeInSeconds = 6300,
                            Position = 2
                        });
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.Racer", b =>
                {
                    b.Property<int>("RacerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RacerId");

                    b.ToTable("Racers");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            FirstName = "Lewis",
                            LastName = "Hamilton"
                        });
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LengthInKm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            TrackId = 1,
                            LengthInKm = 5.89m,
                            Name = "Silverstone Circuit"
                        },
                        new
                        {
                            TrackId = 2,
                            LengthInKm = 3.34m,
                            Name = "Monaco Circuit"
                        });
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.TrackRace", b =>
                {
                    b.Property<int>("TrackRaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Laps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackRaceId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackRaces");

                    b.HasData(
                        new
                        {
                            TrackRaceId = 1,
                            BestTimeInSeconds = 5460,
                            Laps = 52,
                            RaceId = 1,
                            TrackId = 1
                        },
                        new
                        {
                            TrackRaceId = 2,
                            BestTimeInSeconds = 6300,
                            Laps = 78,
                            RaceId = 2,
                            TrackId = 2
                        });
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.RaceParticipation", b =>
                {
                    b.HasOne("RaceParticipationAPI.Models.Racer", "Racer")
                        .WithMany("Participations")
                        .HasForeignKey("RacerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceParticipationAPI.Models.TrackRace", "TrackRace")
                        .WithMany("Participations")
                        .HasForeignKey("TrackRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racer");

                    b.Navigation("TrackRace");
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.TrackRace", b =>
                {
                    b.HasOne("RaceParticipationAPI.Models.Race", "Race")
                        .WithMany("TrackRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceParticipationAPI.Models.Track", "Track")
                        .WithMany("TrackRaces")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.Race", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.Racer", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.Track", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("RaceParticipationAPI.Models.TrackRace", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
